return {}
-- vim.api.nvim_create_user_command('AvanteResizeWide', function ()
--     require('avante.config').override({ windows = { width = 70 } })
--     vim.cmd('AvanteRefresh')
-- end, {})
-- vim.api.nvim_set_keymap('n', '<leader>aw', ':AvanteResizeWide<CR>', {} )

-- vim.api.nvim_create_user_command('AvanteResizeNormal', function ()
--     require('avante.config').override({ windows = { width = 30 } })
--     vim.cmd('AvanteRefresh')
-- end, {})

-- return {
--     "yetone/avante.nvim",
--     version = false, -- Never set this value to "*"! Never!
--     dependencies = {
--         -- required
--         "nvim-treesitter/nvim-treesitter",
--         "stevearc/dressing.nvim",
--         "nvim-lua/plenary.nvim",
--         "MunifTanjim/nui.nvim",
--         -- optional
--         "zbirenbaum/copilot.lua", -- for provider = "copilot"
--     },

--     cmd = { 'AvanteAsk' },
--     keys = { '<leader>aa' },
--     opts = {
--         provider = "copilot",
--         providers = {
--             copilot = {
--                 model = "claude-sonnet-4",
--             },
--         },
--         disabled_tools = {
--             'replace_in_file',
--             'create_file',
--             'rename_file',
--             'delete_file',
--             'create_dir',
--             'rename_dir',
--             'delete_dir',
--             'str_replace',
--             'git_commit',
--             'write_to_file',
--             'insert',
--             'bash',
--             'python',
--             'web_search',
--         },
--         -- auto_suggestions_provider = "copilot",
--         behaviour = {
--             auto_focus_sidebar = false,
--             auto_suggestions = false,
--             auto_suggestions_respect_ignore = false,
--             auto_set_highlight_group = true,
--             auto_set_keymaps = true,
--             auto_apply_diff_after_generation = false,
--             jump_result_buffer_on_finish = false,
--             support_paste_from_clipboard = false,
--             minimize_diff = true,
--             enable_token_counting = true,
--             use_cwd_as_project_root = false,
--             auto_focus_on_diff_view = false,
--             auto_approve_tool_permissions = false,
--         },
--         mappings = {
--             diff = {
--                 ours = "co",
--                 theirs = "ct",
--                 all_theirs = "ca",
--                 both = "cb",
--                 cursor = "cc",
--                 next = "]x",
--                 prev = "[x",
--             },
--             suggestion = {
--                 accept = "<M-l>",
--                 next = "<M-]>",
--                 prev = "<M-[>",
--                 dismiss = "<C-]>",
--             },
--             jump = {
--                 next = "]]",
--                 prev = "[[",
--             },
--             submit = {
--                 normal = "<CR>",
--                 insert = "<C-s>",
--             },
--             cancel = {
--                 normal = { "<C-c>", "<Esc>", "q" },
--                 insert = { "<C-c>" },
--             },
--             sidebar = {
--                 apply_all = "A",
--                 apply_cursor = "a",
--                 retry_user_request = "r",
--                 edit_user_request = "e",
--                 switch_windows = "<Tab>",
--                 reverse_switch_windows = "<S-Tab>",
--                 remove_file = "d",
--                 add_file = "@",
--                 close = { "<Esc>", "q" },
--                 close_from_input = nil, -- e.g., { normal = "<Esc>", insert = "<C-d>" }
--             },
--         },
--         hints = { enabled = true },
--         windows = {
--             position = "right",
--             width = 30,
--             sidebar_header = {
--               enabled = true,
--               align = "center",
--               rounded = true,
--             },
--             input = {
--               prefix = "> ",
--               height = 8, -- Height of the input window in vertical layout
--             },
--             edit = {
--               border = "rounded",
--               start_insert = true, -- Start insert mode when opening the edit window
--             },
--             ask = {
--               floating = false,
--               start_insert = true, -- Start insert mode when opening the ask window
--               border = "rounded",
--             },
--         },
--         highlights = {
--             diff = {
--                 current = "DiffText",
--                 incoming = "DiffAdd",
--             },
--         },
--     },
-- }
